name: test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Create dummy .env
        run: |
          echo "ENGELSYSTEM_USER=demo"      >> .env
          echo "ENGELSYSTEM_PASS=demo"      >> .env
          echo "ENGELSYSTEM_APIKEY=demo"    >> .env
          echo "MATRIX_USER=demo"           >> .env
          echo "MATRIX_PASS=demo"           >> .env

      - name: Run checkin script
        run: node checkin.js
        env:
          NODE_ENV: test
