name: test

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
  schedule:
    - cron: '0 3 * * *'  # nightly

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create dummy .env
        run: |
          echo 'ENGELSYSTEM_USER=demo' >> .env
          echo 'ENGELSYSTEM_PASS=demo' >> .env
          echo 'ENGELSYSTEM_APIKEY=demo' >> .env
          echo 'MATRIX_USER=demo' >> .env
          echo 'MATRIX_PASS=demo' >> .env

      - name: Install Prettier + ESLint
        run: |
          npm init -y
          npm install --save-dev prettier eslint@8

      - name: Run Prettier auto-format
        run: npx prettier --write checkin.js

      - name: Commit formatting if needed
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'chore: auto-format via prettier'

      - name: ESLint (single quotes enforced)
        run: npx eslint@8 checkin.js --no-eslintrc --env node --parser-options=ecmaVersion:2020 --rule 'quotes: [2, "single"]'

      - name: Dry-run execution
        run: node checkin.js
        env:
          NODE_ENV: test
