name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: '0 3 * * *'  # nightly UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install eslint + prettier if missing
      run: |
        npm init -y --scope dummy
        npm install --save-dev eslint prettier

    - name: Create dummy .env
      run: |
        echo "ENGELSYSTEM_USER=demo" >> .env
        echo "ENGELSYSTEM_PASS=demo" >> .env
        echo "ENGELSYSTEM_APIKEY=demo" >> .env
        echo "MATRIX_USER=demo" >> .env
        echo "MATRIX_PASS=demo" >> .env

    - name: Lint Syntax
      run: node -c checkin.js

    - name: Run ESLint
      run: |
        npx eslint checkin.js --no-eslintrc --env node --parser-options=ecmaVersion:2020 --rule 'quotes: [2, "single"]'

    - name: Run Prettier Auto-Fix
      run: npx prettier --write checkin.js

    - name: Commit Formatting (if changed)
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "chore: auto-format via prettier"

    - name: Run Script Dry
      run: node checkin.js
      env:
        NODE_ENV: test
